In [1]:
# Lists

def handler(result):
    inp = input().split()
    command = inp[0]
    values = inp[1:]
    
    if command == 'print':
        print(result)
    else:
        execute = 'result.' + command + "(" + ",".join(value) + ")"
        eval(execute)

In [2]:
# Tuples

n = int(input())

print(hash(tuple(map(int, input().split()))))

5
12
3430014387543


In [3]:
# sWAP cASE

def swap_case(s):
    return s.swapcase()

In [4]:
# String split and join

def split_andjoin(line):
    return "-".join(line.split())

In [5]:
# What's your name

def print_full_name(first_name, last_name):
    print("Hello {} {}!".format(first_name, last_name))

In [6]:
# Mutations

def mutate_string(string, position, character):
    return string[:position] + character + string[postion+1:]

In [7]:
# Find a string

def count_substring(string, sub_string):
    count = 0
    for i in range(len(string) - len(sub_string) + 1):
        if string[i: i+len(sub_string)] == sub_string:
            count += 1
            
    return count

In [8]:
# String validators

s = input()
print(any([char.isalnum() for char in s]))
print(any([char.isalpha() for char in s]))
print(any([char.isdigit() for char in s]))
print(any([char.islower() for char in s]))
print(any([char.isupper() for char in s]))

aD7
True
True
True
True
True


In [10]:
# Text alignment

thickness = int(input())
c = 'H'

for i in range(thickness):
    print((c*i).rjust(thickness-1) + c + (c*i).ljust(thickness-1))
    
for i in range(thickness + 1):
    print((c*thickness).center(thickness*2) + (c*thickness).center(thickness*6))
    
for i in range((thickness+1)//2):
    print((c*thickness*5).center(thickness*6))
    
for i in range(thickness+1):
    print((c*thickness).center(thickness*2) + (c*thickness).center(thickness*6))
    
for i in range(thickness):
    print(((c*(thickness-i-1)).rjust(thickness) + c + (c*(thickness-i-1)).ljust(thickness)).rjust(thickness*6))

4
   H   
  HHH  
 HHHHH 
HHHHHHH
  HHHH            HHHH          
  HHHH            HHHH          
  HHHH            HHHH          
  HHHH            HHHH          
  HHHH            HHHH          
  HHHHHHHHHHHHHHHHHHHH  
  HHHHHHHHHHHHHHHHHHHH  
  HHHH            HHHH          
  HHHH            HHHH          
  HHHH            HHHH          
  HHHH            HHHH          
  HHHH            HHHH          
                HHHHHHH 
                 HHHHH  
                  HHH   
                   H    


In [11]:
# Text wrap

def wrap(string, max_width):
    return textwrap.fill(string, max_width)

In [14]:
# Designer door wrap

height, length = map(int, input().split())

for i in range(0, height//2):
    s = '.|.' * (i*2 + 1)
    print(s.center(length, '-'))

print('WELCOME'.center(length, '-'))

for i in range(height//2 - 1, -1, -1):
    s = '.|.' * (i*2 + 1)
    print(s.center(length, '-'))

5 15
------.|.------
---.|..|..|.---
----WELCOME----
---.|..|..|.---
------.|.------


In [15]:
# String formatting

def print_formatted(number):
    width = len("{0:b}".format(number))
    for i in range(1, number + 1):
        print("{0:{width}d} {0:{width}o} {0:{width}X} {0:{width}b}".format(i, width = width))

In [16]:
# Capitalize

st = input()

print(' '.join(word.capitalize() for word in st.split(' ')))

chris alan
Chris Alan


In [17]:
# Introduction to sets

def average(array):
    return sum(set(array)) / len(set(array))

In [18]:
# No idea

_ = input()
array = input().split()
like = set(input().split())
dislike = set(input().split())

print(sum((i in like) - (i in dislike) for i in array))

3 2
1 5 3
3 1
5 7
1


In [20]:
# Symmetric difference

i, m = input(), set(map(int, input().split()))
i, n = input(), set(map(int, input().split()))

print(*sorted(m.symmetric_difference(n)), sep = '\n')

4
2 4 5 9
4
2 4 11 12
5
9
11
12


In [21]:
# Set add()

print(len(set(input() for i in range(int(input())))))

5
UK
CN
USA
UK
FR
4


In [23]:
# Set discard(), remove(), and pop()

n = int(input())
s = set(map(int, input().split()))

for i in range(int(input())):
    string = input().split()
    
    if string[0] == 'pop':
        s.pop()
    
    elif string[0] == 'remove':
        s.remove(int(string[1]))
        
    elif string[0] == 'discard':
        s.discard(int(string[1]))
    
print(sum(s))

9
1 2 3 4 5
3
pop
remove 2
discard 5
7


In [24]:
# Set union()

_, a = input(), set(input().split())
_, b = input(), set(input().split())

print(len(a.union(b)))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
13


In [25]:
# Set intersection()

_, a = input(), set(input().split())
_, b = input(), set(input().split())

print(len(a.intersection(b)))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
5


In [26]:
# Set difference()

_, a = input(), set(input().split())
_, b = input(), set(input().split())

print(len(a.difference(b)))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
4


In [27]:
# Set symmetric_difference()

_, a = input(), set(input().split())
_, b = input(), set(input().split())

print(len(a.symmetric_difference(b)))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
8


In [28]:
# Set mutation

def handler(a):
    command = input().split()[0]
    new_set = set(map(int, input().split()))
    
    if command == 'intersection_update':
        a.intersection_update(new_set)
        
    if command == 'update':
        a.update(new_set)
        
    if command == 'symmetric_difference_update':
        a.symmetric_difference_update(new_set)
        
    if command == 'difference_update':
        a.difference_update(new_set)

In [30]:
# Captain's room

k = int(input())
room_number_list = list(map(int, input().split()))
captain_room_number = (sum(set(room_number_list))*k - sum(room_number_list)) // (k-1)
print(captain_room_number)

5
1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2
8


In [31]:
# Check subset

for i in range(int(input())):
    _, a = input(), set(map(int, input().split()))
    _, b = input(), set(map(int, input().split()))
    print(a.issubset(b))

2
5
1 2 3 5 6
9
9 8 5 6 3 2 1 4 7
True
1
2
5
3 6 5 4 1
False


In [32]:
# Strict superset

a = set(input().split())

print(all(a > set(input().split()) for _ in range(int(input()))))

1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
2
1 2 3 4 5
100 11 12
False


In [33]:
# Itertoolsproduct()

from itertools import product

a = list(map(int, input().split()))
b = list(map(int, input().split()))

print(*list(product(a, b)))

1 2
3 4
(1, 3) (1, 4) (2, 3) (2, 4)


In [34]:
# Itertoolcominations()

import itertools

s = input().split()
string, number = sorted(s[0]), int(s[1])

for i in range(1, number + 1):
    print(*list(map(''.join, itertools.combinations(string, i))), sep = '\n')

HACK 2
A
C
H
K
AC
AH
AK
CH
CK
HK


In [35]:
# Itertools.permutations()

import itertools

s = input().split()
string, number = sorted(s[0]), int(s[1])

print(*list(map(''.join, itertools.permutations(string, number))), sep = '\n')

HACK 2
AC
AH
AK
CA
CH
CK
HA
HC
HK
KA
KC
KH


In [36]:
# Itertools.combinations_with_replacement()

import itertools

s = input().split()
string, number = sorted(s[0]), int(s[1])
print(*list(map(''.join, itertools.combinations_with_replacement(string, number))), sep='\n')

HACK 2
AA
AC
AH
AK
CC
CH
CK
HH
HK
KK


In [37]:
# Compress the string

from itertools import groupby

print(*[(len(list(c)), int(x)) for x, c in groupby(input())])

1222311
(1, 1) (3, 2) (1, 3) (2, 1)


In [38]:
# Iterables and Iterators

n, number, k = int(input()), input().split().count('a'), int(input())
not_a = 1

for i in range(k):
    not_a = not_a * (n - number - i) / (n - i)
    
print(1 - not_a)

4
a a c d
2
0.8333333333333334


In [39]:
# Maximize it

from itertools import product

k, m = map(int, input().split())
n = (list(map(int, input().split()))[1:] for _ in range(k))
results = (sum(i**2 for i in x) % m for x in product(*n))
print(max(results))

3 1000
2 5 4
3 7 8 9
5 5 7 8 9 10
206


In [40]:
# collectionsCounter()

import collections

number_of_shoes = int(input())
sizes_in_stock = collections.Counter(map(int, input().split()))

total_revenue = 0

for _ in range(int(input())):
    size, price = map(int, input().split())
    
    if sizes_in_stock[size]:
        total_revenue += price
        sizes_in_stock[size] -= 1
        
print(total_revenue)

10
2 3 4 5 6 8 7 6 5 18
6
6 55
6 45
6 55
4 40
18 60
10 50
200


In [43]:
# DefaultDict

from collections import defaultdict

n, m = map(int, input().split())
d = defaultdict(list)

for i in range(1, n+1):
    d[input()].append(str(i))

for i in range(m):
    print(' '.join(d[input()]) or -1)

5 2
a
a
b
a
b
a
1 2 4
b
3 5


In [46]:
# namedtuple()

from collections import namedtuple

n, Student = int(input()), namedtuple('Student', input())

print("{:.2f}".format(sum([int(Student(*input().split()).MARKS) for _ in range(n)]) / n))

5
ID MARKS NAME CLASS
1 97 ray 7
2 50 steven 4
3 91 adrian 9
4 72 stewart 5
5 80 peter 6
78.00


In [48]:
from collections import OrderedDict

order_dictionary = OrderedDict()

for _ in range(int(input())):
    item, price = input().rsplit(' ', 1)
    order_dictionary[item] = ordered_dictionary.get(item, 0) + int(price)
    
[print(item, order_dictionary[item]) for item in order_dictionary]

9
banana 12
potato 30
apple 10
candy 5
apple 10
candy 5
candy 5
candy 6
potato 30
banana 24
potato 90
apple 30
candy 27


[None, None, None, None]

In [49]:
# Word order

from collections import Counter, OrderedDict

class OrderedCounter(Counter, OrderedDict):
    pass

ordered_counter = OrderedCounter(input() for _ in range(int(input())))
print(len(ordered_counter))
print(*ordered_counter.values())

4
bcdef
abcdefg
bcde
bcdef
3
2 1 1


In [50]:
# deque()

from collections import deque

d = deque()

for _ in range(int(input())):
    line = input().split()
    
    if line[0] == 'append':
        d.append(line[1])
        
    elif line[0] == 'pop':
        d.pop()
        
    elif line[0] == 'popleft':
        d.popleft()
        
    elif line[0] == 'appendleft':
        d.qppendleft(line[1])
        
print(*d)

6
append 1
append 2
append 3
append left 4
pop
popleft
2 3


In [52]:
# piling up

from collections import deque

for i in range(int(input())):
    _, n = input(), deque(map(int, input().split()))
    ans = True
    
    for j in range(len(n) - 1):
        if n[0] >= n[1]:
            n.popleft()
            
        elif n[-1] >= n[-2]:
            n.pop()
            
        else:
            ans = False
            break
            
    print('Yes' if ans else 'No')

2
6
4
Yes
3
1 3 2
No


In [53]:
# Calendar module

import calendar

m, d, y = map(int, input().split())
print(calendar.day_name[calendar.weekday(y, m, d)].upper())

08 05 2015
WEDNESDAY


In [1]:
# Time delta

from datetime import datetime as dt

fmt = '%a %d %b %Y %H:%M:%S %z'

for _ in range(int(input())):
    time1 = dt.strptime(input(), fmt)
    time2 = dt.strptime(input(), fmt)
    
    print(int(abs((time1 - time2).total_seconds())))

1
Sun 10 May 2015 13:54:36 -0700
Sun 10 May 2015 13:54:36 -0000
25200


In [2]:
# Exceptions

for _ in range(int(input())):
    a, b = input().split()
    
    try:
        print(int(a) // int(b))
    except BaseException as err:
        print("Error code:", err)

3
1 0
Error code: integer division or modulo by zero
2 $
Error code: invalid literal for int() with base 10: '$'
3 1
3


In [3]:
# Incorrect regex

import re

for _ in range(int(input())):
    try:
        print(bool(re.compile(input())))
    except re.error:
        print('False')

2
.*\+
True
.*+
False


In [4]:
# Array

import numpy

def arrays(arr):
    return numpy.array(arr[::-1], float)

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [5]:
# Shape and reshape

import numpy as np

array = np.array(list(map(int, input().split())))
print(array.reshape(3, 3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
def reverseArray(arr):
    result = arr[::-1]
    return result

arrCount = int(input())
arr = list(map(int, input().rstrip().split()))
result = reverseArray(arr)
print(*result)

4
1 2 3 4
4 3 2 1


In [5]:
# Sock merchant

def sock_merchant(ar):
    list_of_socks = [0 for i in range(101)]
    
    for element in ar:
        list_of_socks[element] = list_of_socks[element] + 1
        
    ans = 0
    
    for sock in list_of_socks:
        ans += sock // 2
        
    return ans

n = int(input().strip())
ar = list(map(int, input().strip().split(' ')))
result = sock_merchant(ar)
print(result)

9
10 20 20 10 10 30 50 10 20
3


In [7]:
# Counting valleys

def counting_valleys(n, s):
    current_level = 0
    count = 0
    for i in range(n):
        if s[i] == 'U':
            current_level += 1
        elif s[i] == 'D':
            current_level -= 1
            if current_level == -1:
                count += 1
    return count

n = int(input().strip())
s = input().strip()
result = counting_valleys(n, s)
print(result)

8
UDDDUDUU
1


In [8]:
# Jumping on the clouds

def jumping_on_clouds(n, c):
    c.append(0)
    ans = 0
    position = 0
    while position < n-1:
        position += (c[position + 2] == 0) + 1
        ans += 1
    return ans

n = int(input())
c = list(map(int, input().rstrip().split()))
print(jumping_on_clouds(n, c))

7
0 0 1 0 0 1 0
4


In [9]:
# Repeated string

def repeated_string(s, n):
    return n // len(s) * s.count('a') + s[0: n%len(s)].count('a')

s = input()
n = int(input())
print(repeated_string(s, n))

aba
10
7


In [10]:
# Array - left rotation

def array_left_rotation(a, k):
    result = a[k:] + a[:k]
    return result

n, k = map(int, input().split())
a = list(map(int, input().split()))
print(*array_left_rotation(a, k))

5 4
1 2 3 4 5
5 1 2 3 4


In [12]:
# 2D array

def hourglasses(arr, i, j):
    return sum(arr[i][j:j+3]) + arr[i+1][j+1] + sum(arr[i+2][j:j+3])

arr = []
for i in range(6):
    arr.append(list(map(int, input().split())))
    
ans = hourglasses(arr, 0, 0)

for i in range(4):
    for j in range(4):
        ans = max(ans, hourglasses(arr, i, j))
print(ans)

1 1 1 0 0 0
0 1 0 0 0 0
1 1 1 0 0 0
0 0 2 4 4 0
0 0 0 2 0 0
0 0 1 2 4 0
19


In [3]:
# Transpose and flatten

import numpy

n, m = map(int, input().split())
ar = []

for i in range(n):
    row = list(map(int, input().split()))
    ar.append(row)

np_ar = numpy.array(ar)
print(numpy.transpose(np_ar))
print(np_ar.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [4]:
# Concatenate

import numpy as np

n, m, p = map(int, input().split())

ar1 = []
ar2 = []

for i in range(n):
    tmp = list(map(int, input().split()))
    ar1.append(tmp)
    
for i in range(m):
    tmp = list(map(int, input().split()))
    ar2.append(tmp)
    
np_ar1 = np.array(ar1)
np_ar2 = np.array(ar2)

print(np.concatenate((np_ar1, np_ar2), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [7]:
# Zeros and ones

import numpy as np

n_ar = list(map(int, input().split()))
n = tuple(n_ar)

print(np.zeros(n, dtype = np.int))
print(np.ones(n, dtype = np.int))

3 3
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [8]:
# Eye and identity

import numpy as np

n, m = map(int, input().split())
print(np.eye(n, m, k = 0))

3 2
[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [9]:
# Array Mathematics

import numpy as np

n, m = map(int, input().split())
ar1 = []
ar2 = []

for i in range(n):
    tmp = list(map(int, input().split()))
    ar1.append(tmp)
    
for i in range(n):
    tmp = list(map(int, input().split()))
    ar2.append(tmp)
    
np_ar1 = np.array(ar1)
np_ar2 = np.array(ar2)

print(np_ar1 + np_ar2)
print(np_ar1 - np_ar2)
print(np_ar1 * np_ar2)
print(np_ar1 // np_ar2)
print(np_ar1 % np_ar2)
print(np_ar1 ** np_ar2)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [10]:
# Floor, ceil, and rint

import numpy as np

np_ar = np.array(list(map(float, input().split())), float)

print(np.floor(np_ar))
print(np.ceil(np_ar))
print(np.rint(np_ar))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


In [11]:
# Sum and Prod

import numpy as np

n, m = map(int, input().split())
ar = []

for i in range(n):
    tmp = list(map(int, input().split()))
    ar.append(tmp)
    
np_ar = np.array(ar)
s = np.sum(np_ar, axis = 0)
print(np.prod(s))

2 2
1 2
3 4
24


In [12]:
# Min and Max

import numpy as np

n, m = map(int, input().split())
ar = []

for i in range(n):
    tmp = list(map(int, input().split()))
    ar.append(tmp)
    
np_ar = np.array(ar)
print(np.max(np.min(np_ar, axis = 1)))

4 2
2 5
3 7
1 3
4 0
3


In [13]:
# Mean, var, and std

n, m = map(int, input().split())
ar = []

for i in range(n):
    tmp = list(map(int, input().split()))
    ar.append(tmp)
    
np_ar = np.array(ar)

print(np.mean(np_ar, axis = 1))
print(np.var(np_ar, axis = 0))
print(np.std(np_ar))

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.118033988749895


In [14]:
# Dot and Cross

import numpy as np

n = int(input())
ar1 = []
ar2 = []

for i in range(n):
    tmp = list(map(int, input().split()))
    ar1.append(tmp)
    
for i in range(n):
    tmp = list(map(int, input().split()))
    ar2.append(tmp)
    
np_ar1 = np.array(ar1)
np_ar2 = np.array(ar2)

print(np.dot(np_ar1, np_ar2))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [15]:
# Inner and Outer

import numpy

np_ar1 = numpy.array(list(map(int,input().split())))
np_ar2 = numpy.array(list(map(int,input().split())))

print(numpy.inner(np_ar1, np_ar2))
print(numpy.outer(np_ar1, np_ar2))

0 1
2 3
3
[[0 0]
 [2 3]]


In [17]:
# Polynomial

import numpy as np

p = np.array(list(map(float, input().split())), float)
x = float(input())

print(np.polyval(p, x))

1 2 3
1
6.0


In [21]:
# Linear Algebra

import numpy as np

n = int(input())
ar = []

for i in range(n):
    tmp = list(map(float, input().split()))
    ar.append(tmp)
    
np_ar = np.array(ar, float)
print(round(np.linalg.det(np_ar), 2))

2
1.1 1.1
1.1 1.1
0.0


In [22]:
# WordsScore

def is_vowel(letter):
    return letter in ['a', 'e', 'i', 'o', 'u', 'y']

def score_words(words):
    score = 0
    for word in words:
        num_vowels = 0
        for letter in word:
            if is_vowel(letter):
                num_vowels += 1
        if num_vowels % 2 == 0:
            score += 2
        else:
            score += 1
    return score